### ISSUE TITLE
Master branch

### ISSUE THREAD

**Issue by awoods** [fcrepo4-labs/fcrepo4-upgrade-utils#1]
We probably need one of those ;)

**Comment by ajs6f** [comment]
Only if there is actually one single artifact to be produced from the code in this repo. Otherwise, you might as well have different branches for different products, a la Github pages.

Actually, what _is_ the intention for the contents of this repo? Is it the place to put version-to-version migration tools?

**Comment by awoods** [comment]
My understanding was exactly that: This repo would be a place to put version-to-version migration tools.

**Comment by ajs6f** [comment]
Ok, cool. I guess in that case we are talking about a single artifact.

**Comment by escowles** [comment]
Yes, my expectation was that we'd create a new utility every time there was a version-to-version migration.  But that raises some questions about how to package and organize them. If people are a few versions behind, do they need to run several of them, or is there some combo updater?  Should the updaters be named like Migrate4.2.0to4.3.0 to make it clear what versions are involved?

**Comment by awoods** [comment]
We can organize this repo in a number of different ways. Any of them are fine with me as long as we remain consistent:
- Make an appropriately named branch for each migration?
- Make an appropriately named maven project for each migration (in separate directories)?
- Make an appropriately named maven project for each migration (in separate directories, with a top-level pom.xml)?

**Comment by escowles** [comment]
I imagine as a practical matter, we will want to release these migration utilities as executable JARs, so repository administrators don't have setup Maven and download a ton of dependencies in order to use them.  That seems like it maps best to the one-tool-per-branch approach, but I'm not really familiar with how the release process works.

**Comment by awoods** [comment]
There should be no impact on the release process if we do not use a "master" branch. In other words, none of the tooling has an expectation of the existence of a "master" branch.
If we go the separate branch per migration approach, let's establish a naming convention that can be documented in the README.md for the repository.

**Comment by escowles** [comment]
Naming the branches according to the migration versions seems like a good idea, something like: "from-$FROM-to-$TO-$NAME", so the first branch could be "from-4.2-to-4.3-tech-metadata".  Does that sound reasonable?

**Comment by awoods** [comment]
That sounds reasonable... although I am not sure "-tech-metadata" is necessary since there is only one migration tool between versions. So:
`from-4.2-to-4.3` may be adequate.

**Comment by ajs6f** [comment]
I'll go even further-- if all of the tools here are migrations, then just `4.2-4.3` should be enough, i.e. `oldVersion-newVersion`.

**Comment by escowles** [comment]
:+1:  to `oldversion-newVersion` -- and if we want to add a tool that isn't a migration, we can decide on an appropriate naming scheme when that comes up.

**Comment by awoods** [comment]
:+1:

**Comment by awoods** [comment]
Resolved: https://github.com/fcrepo4-labs/fcrepo4-upgrade-utils/branches
